#ifndef QT_DATA_CMAKE_GENERATOR_HTML_GLOBAL_H
#define QT_DATA_CMAKE_GENERATOR_HTML_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_DATA_CMAKE_GENERATOR_HTML_LIBRARY)
#define QT_DATA_CMAKE_GENERATOR_HTML_EXPORT Q_DECL_EXPORT
#else
#define QT_DATA_CMAKE_GENERATOR_HTML_EXPORT Q_DECL_IMPORT
#endif

#endif // QT_DATA_CMAKE_GENERATOR_HTML_GLOBAL_H
